# Rule Configuration
rules:
  attribute-quotes:
    - 2
  border-zero:
    - convention: 'none'
  brace-style:
    -
      style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  empty-args:
    - 2
    - include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations:
    - 2
  extends-before-mixins:
    - 2
  final-newline:
    - 2
    - include: false
  force-attribute-nesting:
    - 0
  force-element-nesting:
    - 0
  force-pseudo-nesting:
    - 0
  function-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 4
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 0
  mixins-before-declarations:
    - 0
  nesting-depth:
    - 2
    - max-depth: 4
  no-attribute-selectors:
    - 2
  no-color-hex:
    - 0
  no-color-keywords:
    - 2
  no-color-literals:
    - 0
  no-combinator:
    - 0
  no-css-comments:
    - 0
  no-duplicate-properties:
    - 2
  no-empty-rulesets:
    - 2
  no-important:
    - 0
  no-invalid-hex:
    - 2
  no-mergeable-selectors:
    - 2
  no-misspelled-properties:
    - 2
  no-trailing-whitespace:
    - 2
  no-transition-all:
    - 2
  no-vendor-prefixes:
    - 0
  no-universal-selectors:
    - 0
  one-declaration-per-line:
    - 2
  property-sort-order:
    - 2
    - order: 'alphabetical'
  quotes:
    - 2
    - style: 'single'
  shorthand-values:
    - 2
    - allowed-shorthands: [1, 2, 3]
  single-line-per-selector:
    - 2
  space-after-bang:
    - 2
    - include: 'false'
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes:
    - 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  zero-unit:
    - 0